name: Build Android APK
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          
      - name: set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21' # Version updated to fix Java 21 error
          distribution: 'temurin'

      - name: Install & Sync
        run: |
          npm install
          # Dummy files for Cordova compatibility
          mkdir -p android/app/src/main/assets/www
          mkdir -p android/app/capacitor-cordova-android-plugins
          echo "ext {}" > android/app/capacitor-cordova-android-plugins/cordova.variables.gradle
          echo "<html></html>" > android/app/src/main/assets/www/index.html
          npx cap sync android
          
      - name: Build APK
        run: |
          cd android
          chmod +x gradlew
          ./gradlew assembleDebug --no-daemon
          
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: dairy-wala-app
          path: android/app/build/outputs/apk/debug/app-debug.apk
